---
- include_role:
    name: andrewrothstein.unarchivedeps
- include_role:
    name: andrewrothstein.temurin
  vars:
    openjdk_app: jre
- name: check for druid installation in {{ druid_install_dir }}
  become: true
  become_user: root
  stat:
    path: '{{ druid_install_dir }}'
  changed_when: false
  register: druid_binary
- when: not druid_binary.stat.exists
  block:
    - name: downloading {{ druid_tgz_url }}
      become: true
      become_user: root
      get_url:
        url: '{{ druid_tgz_url }}'
        dest: '{{ druid_tmp_tgz }}'
        checksum: '{{ druid_checksum }}'
        mode: 0644
    - name: unarchive {{ druid_tmp_tgz }} to {{ druid_install_parent_dir }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ druid_tmp_tgz }}'
        dest: '{{ druid_install_parent_dir }}'
        creates: '{{ druid_install_dir }}'
  always:
    - name: rm {{ druid_tmp_tgz }}
      become: true
      become_user: root
      file:
        path: '{{ druid_tmp_tgz }}'
        state: absent
- name: linking {{ druid_link_dir }} to {{ druid_install_dir }}
  become: true
  become_user: root
  file:
    src: '{{ druid_install_dir }}'
    dest: '{{ druid_link_dir }}'
    state: link
- name: include druid in the default sh path...
  become: true
  become_user: root
  with_items:
    - f: druid.sh
      d: /etc/profile.d
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m|default("0644") }}'
