---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Installing andrewrothstein.temurin
  ansible.builtin.include_role:
    name: andrewrothstein.temurin
  vars:
    temurin_app: jre
- name: Check for druid installation in {{ druid_install_dir }}
  become: true
  become_user: root
  ansible.builtin.stat:
    path: '{{ druid_install_dir }}'
  changed_when: false
  register: druid_binary
- name: Downloading and installing Apache Druid
  when: not druid_binary.stat.exists
  block:
    - name: Downloading {{ druid_tgz_url }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ druid_tgz_url }}'
        dest: '{{ druid_tmp_tgz }}'
        checksum: '{{ druid_checksum }}'
        mode: '644'
    - name: Unarchive {{ druid_tmp_tgz }} to {{ druid_install_parent_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ druid_tmp_tgz }}'
        dest: '{{ druid_install_parent_dir }}'
        creates: '{{ druid_install_dir }}'
  always:
    - name: Rm {{ druid_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ druid_tmp_tgz }}'
        state: absent
- name: Linking {{ druid_link_dir }} to {{ druid_install_dir }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ druid_install_dir }}'
    dest: '{{ druid_link_dir }}'
    state: link
- name: Include druid in the default sh path...
  become: true
  become_user: root
  with_items:
    - f: druid.sh
      d: /etc/profile.d
  ansible.builtin.template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m | default("644") }}'
